# Generated by Django 2.2.12 on 2022-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='totle_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
