# Generated by Django 2.2.12 on 2022-03-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_totle_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='totle_view',
            new_name='total_view',
        ),
    ]
