# Generated by Django 2.2.12 on 2022-03-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='文章tag')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticlePost', verbose_name='文章id')),
            ],
            options={
                'db_table': 'Article_tag',
            },
        ),
    ]
