# Generated by Django 2.2.12 on 2022-03-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_tag',
        ),
    ]
