# Generated by Django 2.2.12 on 2022-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='tags',
        ),
    ]
