# Generated by Django 2.2.12 on 2022-03-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_author_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
