# Generated by Django 2.2.12 on 2022-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20220329_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='tags',
            field=models.CharField(default='speical', max_length=100),
        ),
    ]
