# Generated by Django 2.2.12 on 2022-04-22 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='drf_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Title (*)')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('status', models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='s', max_length=1, null=True, verbose_name='status(*)')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create_Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articels', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'drf_Article',
                'db_table': 'drf_Article',
                'ordering': ['-create_date'],
            },
        ),
    ]
